In [1]:
import numpy as np
from numpy import *

In [2]:
x0 = np.array([[1,1.1]])
x1 = np.array([[1.9, 2.2]])
x2 = np.array([[2.9, 3]])
A = np.squeeze(np.array([x0,x1,x2]))
y = np.array([[1,2,3]])
A,y

(array([[1. , 1.1],
        [1.9, 2.2],
        [2.9, 3. ]]), array([[1, 2, 3]]))

In [9]:
"""
min loss(A, w, gamma, y)
subject to ||w||^2 - t <= 0
"""

'\nmin loss(A, w, gamma, y)\nsubject to ||w||^2 - t <= 0\n'

In [14]:
def constraint_g (w, t):
    """
    Inequality constraint g
    
    Parameters
    ----------
    w array of weights.
    t value, regularization parameter.
    
    """
    return np.linalg.norm(w)**2 - t

In [16]:
constraint_g(w, 3)

1.7246112077518285

In [17]:
from scipy.optimize import minimize
from scipy.optimize import LinearConstraint
from scipy.optimize import Bounds
from scipy.optimize import NonlinearConstraint

In [18]:
nonlinear_constraint = NonlinearConstraint()

TypeError: __init__() missing 3 required positional arguments: 'fun', 'lb', and 'ub'

In [ ]:
# Explanation of data
#
#    The death rate is to be represented as a function of other variables.
#
#    There are 60 rows of data. Each point has 15 features:
#
#      A1,  the average annual precipitation;
#      A2,  the average January temperature;
#      A3,  the average July temperature;
#      A4,  the size of the population older than 65;
#      A5,  the number of members per household;
#      A6,  the number of years of schooling for persons over 22;
#      A7,  the number of households with fully equipped kitchens;
#      A8,  the population per square mile; 
#      A9,  the size of the nonwhite population;
#      A10, the number of office workers;
#      A11, the number of families with an income less than $3000;
#      A12, the hydrocarbon pollution index;
#      A13, the nitric oxide pollution index;
#      A14, the sulfur dioxide pollution index;
#      A15, the degree of atmospheric moisture.
#
#    The output is:
#      Y,   the death rate.
# A and y; last column is y

In [19]:
import pandas as pd
df = pd.DataFrame(pd.read_csv('deathrate_instance_python.dat', header=None, sep="\s+"))
df.columns = ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'Y']

In [20]:
Y = df['Y']
X = df.drop(columns=['Y'])

In [21]:
Ymat = Y.values
Xmat = X.values

In [22]:
w = np.squeeze(np.random.rand(1,15)) # random weights
gamma = 500

In [23]:
wopt = np.array([0.48824,-0.0463881,0.102978,-0.0377061,0.00490736,-0.0339172,-0.255786,0.00564845,0.649708,-0.12622,0.213407,-0.207831,0.109842,0.376641,0.00995978])
gammaopt = 895.141
loss_func(np.array([wopt, gammaopt])) # valor optim

61484.650716435746

In [24]:
"""
MINOS 5.51: optimal solution found.
133 iterations, objective 61484.65464
Nonlin evals: obj = 361, grad = 360, constrs = 361, Jac = 360.

norm2_w = -10785.1
gamma = 895.141

w [*] :=
 1   0.48824
 2  -0.0463881
 3   0.102978
 4  -0.0377061
 5   0.00490736
 6  -0.0339172
 7  -0.255786
 8   0.00564845
 9   0.649708
10  -0.12622
11   0.213407
12  -0.207831
13   0.109842
14   0.376641
15   0.00995978

"""
1

1

In [25]:
np.ones((1,5)) @ np.ones((1,5)).T

array([[5.]])

In [27]:
import numpy as np
from scipy.optimize import minimize
from scipy.optimize import LinearConstraint
from scipy.optimize import Bounds

# rosenbrock function and first and second derivatives already available from scipy
from scipy.optimize import rosen
from scipy.optimize import rosen_der
from scipy.optimize import rosen_hess

linear_constraint = LinearConstraint([[1, 2], [2, 1]], [-np.inf, 1], [0.7, 1])
bounds = Bounds([0.0, -1.0], [1.0, 2.0])
x0=[-2,-10]
sol = minimize(rosen, x0, method='trust-constr', jac=rosen_der, hess= rosen_hess,
               constraints=linear_constraint, options={'verbose': 1},bounds=bounds)
#print(sol)

`gtol` termination condition is satisfied.
Number of iterations: 23, function evaluations: 21, CG iterations: 19, optimality: 1.92e-09, constraint violation: 0.00e+00, execution time: 0.063 s.


In [43]:
rosen_hess([-1,0])

array([[1202,  400],
       [ 400,  200]])

In [180]:
# Loss func loss(x)
def loss_func (x):
    """
    Objective function: loss / cost function.
    
    Parameters
    ----------
    w array of weights.
    gamma array of intercepts.
    
    Returns
    -------
    The objective function loss(x) evaluated at {w, gamma}.
    
    """
    w = np.asarray(x[:-1]).T
    gamma = x[-1]
    
    cost = (1/2) * ((Xmat @ w) + gamma - Ymat).T @ ((Xmat @ w) + gamma - Ymat)
  
    return np.squeeze(cost)

In [181]:
wopt = [0.48824,-0.0463881,0.102978,-0.0377061,0.00490736,-0.0339172,-0.255786,0.00564845,0.649708,-0.12622,0.213407,-0.207831,0.109842,0.376641,0.00995978,895.141]
loss_func2(wopt) # valor optim

61484.650716435746

In [182]:
def loss_grad (x): 
    """
    Gradient of the objective function (loss / cost function).
    
    Parameters
    ----------
    A matrix with x arrays at the rows.
    w array of weights.
    gamma array of intercepts.
    y array of f(x).
    
    Returns
    -------
    Array of the gradient of the objective function loss(x) 
    evaluated at {w, gamma}.
    
    """
    w = np.asarray(x[:-1]).T
    gamma = x[-1]
    
    g_cost_comp1 = Xmat.T @ ((Xmat @ w) + gamma - Ymat)
    g_cost_comp2 = np.ones(len(Ymat)).T @ ((Xmat @ w) + gamma - Ymat)
    
    return np.concatenate((g_cost_comp1, g_cost_comp2), axis=None)

In [184]:
loss_grad(wopt) # valor optim

array([-1.05322859e+04,  9.99806306e+02, -2.22295893e+03,  8.13127974e+02,
       -1.05927484e+02,  7.31350810e+02,  5.51550115e+03, -2.10784096e+02,
       -1.40146068e+04,  2.72154380e+03, -4.60357165e+03,  4.48211610e+03,
       -2.36983501e+03, -8.12547179e+03, -2.16150552e+02, -2.28754456e-02])

In [185]:
def loss_hess (x):
    """
    Hessian matrix of the objective function (loss / cost function).
    
    Parameters
    ----------
    w array of weights.
    gamma array of intercepts.
    
    Returns
    -------
    Matrix of the Hessian of the objective function loss(x) 
    evaluated at {w, gamma}.
    
    """
    w = np.asarray(x[:-1]).T
    gamma = x[-1]
    
    block_top_left = Xmat.T @ Xmat
    block_top_right = Xmat.T @ np.ones(len(Ymat))
    
    block_bottom_left = np.ones(len(Ymat)).T @ Xmat
    block_bottom_right = len(Ymat)
    
    H[:-1,:-1] = block_top_left
    H[:-1,-1] = block_top_right
    
    H[-1,:-1] = block_bottom_left
    H[-1,-1] = block_bottom_right
    
    return H

In [186]:
#loss_hess2(wopt)