In [3]:
import numpy as np
from numpy import *

In [19]:
x0 = np.array([[1,1.1]])
x1 = np.array([[1.9, 2.2]])
x2 = np.array([[2.9, 3]])
A = np.squeeze(np.array([x0,x1,x2]))
y = np.array([[1,2,3]])
A,y

(array([[1. , 1.1],
        [1.9, 2.2],
        [2.9, 3. ]]), array([[1, 2, 3]]))

In [125]:
w = np.array([[1, 1]])
gamma = np.array([[0, 0, 0]]).T
A*w + gamma - y.T
w @ A.T + gamma.T 

array([[2.1, 4.1, 5.9]])

In [126]:
# Loss func f(x)
def loss (A, w, gamma, y):
    cost = (1/2)*(w @ A.T + gamma.T - y) @ (w @ A.T + gamma.T - y).T
    return np.squeeze(cost)

In [127]:
loss(A, w, gamma, y)

array(7.015)

In [108]:
def g_loss (A, w, gamma, y): # ??
    g_cost = -2* (y - w @ A.T + gamma.T) @ A
    return np.squeeze(g_cost)

In [109]:
g_loss(A, w, gamma, y)

array([27.  , 29.06])

In [128]:
def hess_loss (A, w, gamma, y):
    return A.T @ A

In [129]:
hess_loss(A, w, gamma, y)

array([[13.02, 13.98],
       [13.98, 15.05]])

In [ ]:
lambda w: 