In [2]:
import numpy as np
from numpy import *

In [4]:
x0 = np.array([[1,1.1]])
x1 = np.array([[1.9, 2.2]])
x2 = np.array([[2.9, 3]])
A = np.squeeze(np.array([x0,x1,x2]))
y = np.array([[1,2,3]])
A,y

(array([[1. , 1.1],
        [1.9, 2.2],
        [2.9, 3. ]]), array([[1, 2, 3]]))

In [5]:
w = np.array([[1, 1]])
gamma = np.array([[0, 0, 0]]).T
A*w + gamma - y.T
w @ A.T + gamma.T 

array([[2.1, 4.1, 5.9]])

In [4]:
# Loss func f(x)
def loss (A, w, gamma, y):
    cost = (1/2)*(w @ A.T + gamma.T - y) @ (w @ A.T + gamma.T - y).T
    return np.squeeze(cost)

In [5]:
loss(A, w, gamma, y)

array(7.015)

In [6]:
def g_loss (A, w, gamma, y): # ??
    g_cost = -2* (y - w @ A.T + gamma.T) @ A
    return np.squeeze(g_cost)

In [7]:
g_loss(A, w, gamma, y)

array([27.  , 29.06])

In [8]:
def hess_loss (A, w, gamma, y):
    return A.T @ A

In [9]:
hess_loss(A, w, gamma, y)

array([[13.02, 13.98],
       [13.98, 15.05]])

In [10]:
lambda w: 

SyntaxError: invalid syntax (<ipython-input-10-0bd6d16b2796>, line 1)

In [6]:
def norma(w):
    n = 0
    for i in range (0,len(w.T)):
            n += int(w.T[i])
    return n

In [13]:
norma(w)

2